<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	<GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Application\Commands\Abstractions\**" />
    <Compile Remove="Application\Queries\QueryParameters\**" />
    <Content Remove="Application\Commands\Abstractions\**" />
    <Content Remove="Application\Queries\QueryParameters\**" />
    <EmbeddedResource Remove="Application\Commands\Abstractions\**" />
    <EmbeddedResource Remove="Application\Queries\QueryParameters\**" />
    <None Remove="Application\Commands\Abstractions\**" />
    <None Remove="Application\Queries\QueryParameters\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="11.0.1" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="11.0.0" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.2.2" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.2.2" />
    <PackageReference Include="MediatR" Version="10.0.1" />
    <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="10.0.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TrialsSystem.UsersService.Infrastructure\TrialsSystem.UsersService.Infrastructure.csproj" />
  </ItemGroup>

</Project>
